Repository DKhan1998/cne-sfia2-project, pull requests merged in 2020-09, with the labels that each got.

#1 [CSP-4] Added core file structure && successfully cloned repo
  .gitignore
  Jenkinsfile
  backend/Dockerfile
  docker-compose.yaml
  frontend/Dockerfile
  nginx.conf
Labels: documentation

#2 [CSP-4] development
  .gitignore
  .idea/.gitignore
  .idea/cne-sfia2-project.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Dockerfile
  backend/Dockerfile
  docker-compose.yaml
  frontend/Dockerfile
Labels: documentation

#3 Csp 4 development
  Jenkinsfile
  docker-compose.yaml
  nginx.conf
Labels: documentation, good first issue

#4 [CSP-10] - Jenkins development
  .idea/misc.xml
  Dockerfile
  Jenkinsfile
  backend/Dockerfile
  docker-compose.yaml
  nginx.conf
Labels: bug

#6 [csp-10] Jenkinsfile dev
  Dockerfile
  Jenkinsfile
Labels: documentation, enhancement

#5 Add a Codacy badge to README.md
  README.md
Labels: documentation

#11 Begun progress with testing application.
  Jenkinsfile
Labels: documentation

#12 [CSP-1] Configured Ansible Playbook
  .gitignore
  Ansible/Dockerfile.sh
  Ansible/Jenkins_Install.sh
  Ansible/inventory.ini
  Ansible/playbook.yaml
  Jenkinsfile
  playbook.yml
Labels: documentation, enhancement
